import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, extname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const excludedDirectories = new Set([
  '.git', 'node_modules', 'www', 'docs', 'tests', 'assets', 'public', 'android', 'functions', 'scripts', 'tools', 'mockups',
]);

function walk(directory) {
  const files = [];
  for (const entry of readdirSync(directory)) {
    const absolute = resolve(directory, entry);
    const projectPath = relative(root, absolute).replaceAll('\\', '/');
    const top = projectPath.split('/')[0];
    if (statSync(absolute).isDirectory()) {
      // Skip dot-directories (.git, .github, .codex-worktrees, …) so a
      // Codex worktree checkout on disk cannot pollute the source scan.
      if (!entry.startsWith('.') && !excludedDirectories.has(top)) files.push(...walk(absolute));
      continue;
    }
    files.push({
      path: projectPath,
      source: readFileSync(absolute, 'utf8'),
      extension: extname(entry),
    });
  }
  return files;
}

const runtimeFiles = walk(root);
const jsFiles = runtimeFiles.filter((file) => file.extension === '.js');
const cssFiles = runtimeFiles.filter((file) => file.extension === '.css');

function countMatches(files, expression) {
  return files.reduce((sum, file) => sum + (file.source.match(expression) || []).length, 0);
}

test('runtime Firebase access is confined to the data boundary', () => {
  const boundaryPattern = /firebase-firestore\.js|(?:from\s+|import\()['"][^'"]*data\/data-core\.js['"]/;
  const offenders = jsFiles
    .filter((file) => boundaryPattern.test(file.source))
    .map((file) => file.path)
    .filter((path) => path !== 'data.js' && !path.startsWith('data/'));

  assert.deepEqual(offenders.sort(), [], 'UI/feature modules must not access Firestore directly');
});

test('runtime markup has no inline business event handlers', () => {
  const uiFiles = runtimeFiles.filter((file) => ['.js', '.html'].includes(file.extension));
  const offenders = uiFiles
    .filter(file => /\son(?:click|change|input|submit|touchstart|touchend|keydown|keyup|focus|blur)=/i.test(file.source))
    .map(file => file.path);
  assert.deepEqual(offenders, [], `inline event handlers remain: ${JSON.stringify(offenders)}`);
});

test('window assignments are limited to platform, PWA, and debug bridges', () => {
  const allowedGlobals = new Set([
    '__BUILD_INFO', '__debugHarvest', '__expertAddEquipment', '__expertDebug',
    '__getTomatoFcmSWRegistration', '__migrateGymV1', '__migrationBackup',
    '__migrationCleanupGyms', '__migrationRollback', '__refreshTomatoAppSWRegistration',
    '__requestTomatoApkInstall', '__requestTomatoAppRefresh', '__showAppUpdateBanner',
    '__showDietPremiumReportPreview', '__tomatoAppReady', '__tomatoAppSWRegistration',
    '__tomatoAppSWRegistrationPromise', '__tomatoFcmSWRegistrationPromise',
    '__tomatoUpdateBannerState', '__tomatoWearWorkoutBridge', '__wtHasActiveDraft',
    '__wtPersistActiveDraft', 'haptic',
  ]);
  const assignmentPattern = /window\.([A-Za-z_$][A-Za-z0-9_$]*)\s*=(?!=)/g;
  const offenders = [];
  for (const file of jsFiles) {
    for (const match of file.source.matchAll(assignmentPattern)) {
      if (!allowedGlobals.has(match[1])) offenders.push(`${file.path}:${match[1]}`);
    }
  }
  assert.deepEqual(offenders, [], `unauthorized business globals remain: ${JSON.stringify(offenders)}`);
});

test('CSS important debt cannot grow above the Phase 0 baseline', () => {
  const authoredCssFiles = cssFiles.filter((file) => file.path !== 'style.css');
  const counts = authoredCssFiles.map((file) => ({
    path: file.path,
    count: file.source.split('!important').length - 1,
  }));
  const count = counts.reduce((sum, file) => sum + file.count, 0);
  assert.ok(count <= 40,
    `CSS !important debt ${count} exceeds baseline 40: ${JSON.stringify(counts)}`);
});

test('feature CSS ownership generates one standalone WebView-safe entry bundle and documents bounded large-file exceptions', () => {
  const byPath = new Map(cssFiles.map(file => [file.path, file]));
  const shell = byPath.get('style.css');
  assert.ok(shell, 'style.css standalone entry bundle should exist');
  assert.match(shell.source, /GENERATED by scripts\/generate-style-entry\.mjs/);
  assert.match(shell.source, /SOURCE: styles\/features\/home-life-zone\.css/);
  assert.match(shell.source, /SOURCE: styles\/accessibility\.css/);
  assert.ok(byPath.has('styles/compatibility.css'), 'compatibility rules must stay outside the entry manifest');

  const allowedLargeFiles = new Set([
    'styles/features/home-life-zone.css',
    'styles/features/workout-day-sheet.css',
    'styles/workout/expert-mode.css',
  ]);
  const unexpected = cssFiles
    .map(file => ({ path: file.path, lines: file.source.split(/\r?\n/).length }))
    .filter(file => file.path !== 'style.css' && file.lines > 1200 && !allowedLargeFiles.has(file.path));
  assert.deepEqual(unexpected, [], `undocumented CSS files exceed 1,200 lines: ${JSON.stringify(unexpected)}`);
});

test('runtime modules use canonical URLs without per-file query versions', () => {
  const offenders = runtimeFiles
    .filter(file => ['.js', '.html', '.css'].includes(file.extension) && file.source.includes('?v='))
    .map(file => file.path);
  assert.deepEqual(offenders, [], `legacy module query versions remain: ${JSON.stringify(offenders)}`);
});
